data:
  UL18:
    EGamma:
      datasets:
        - /EGamma/Run2018A-12Nov2019_UL2018-v2/MINIAOD
        - /EGamma/Run2018B-12Nov2019_UL2018-v2/MINIAOD
        - /EGamma/Run2018C-12Nov2019_UL2018-v2/MINIAOD
        - /EGamma/Run2018D-12Nov2019_UL2018-v4/MINIAOD
    Muon:
      datasets:
        - /SingleMuon/Run2018A-12Nov2019_UL2018-v2/MINIAOD
        - /SingleMuon/Run2018B-12Nov2019_UL2018-v2/MINIAOD
        - /SingleMuon/Run2018C-12Nov2019_UL2018-v2/MINIAOD
        - /SingleMuon/Run2018D-12Nov2019_UL2018-v4/MINIAOD

  Run3_24:
    EGamma:
      datasets:
        - /EGamma0/Run2024B-PromptReco-v1/MINIAOD
        - /EGamma0/Run2024C-PromptReco-v1/MINIAOD
        - /EGamma0/Run2024D-PromptReco-v1/MINIAOD
        - /EGamma0/Run2024E-PromptReco-v2/MINIAOD
        - /EGamma1/Run2024B-PromptReco-v1/MINIAOD
        - /EGamma1/Run2024C-PromptReco-v1/MINIAOD
        - /EGamma1/Run2024D-PromptReco-v1/MINIAOD
        - /EGamma1/Run2024E-PromptReco-v2/MINIAOD
    Muon:
      datasets:
        - /Muon0/Run2024B-PromptReco-v1/MINIAOD
        - /Muon0/Run2024C-PromptReco-v1/MINIAOD
        - /Muon0/Run2024D-PromptReco-v1/MINIAOD
        - /Muon0/Run2024E-PromptReco-v2/MINIAOD
        - /Muon1/Run2024B-PromptReco-v1/MINIAOD
        - /Muon1/Run2024C-PromptReco-v1/MINIAOD
        - /Muon1/Run2024D-PromptReco-v1/MINIAOD
        - /Muon1/Run2024E-PromptReco-v2/MINIAOD

mc:
  UL18:
    ttbar_dileptonic:
      datasets:
        - /TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
    ttbar_semileptonic:
      datasets:
        - /TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
    qcd:
      dataset_queries:
        - /QCD_Pt*_TuneCP5_13TeV_pythia8/RunIISummer20UL18MiniAODv2-*/MINIAODSIM
    vjets:
      dataset_queries:
        - /WJetsToLNu*_TuneCP5_13TeV*/RunIISummer20UL18MiniAODv2-*/MINIAODSIM
        - /DYJetsToLL_M-50*_TuneCP5_13TeV*/RunIISummer20UL18MiniAODv2-*/MINIAODSIM
    single_top:
      dataset_queries:
        - /ST_*_TuneCP5_13TeV*/RunIISummer20UL18MiniAODv2-*/MINIAODSIM

  Run3_24:
    ttbar_dileptonic:
      datasets:
        - /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
    ttbar_semileptonic:
      datasets:
        - /TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
    qcd:
      datasets:
        - /QCD_Bin-PT-80to120_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /QCD_Bin-PT-120to170_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /QCD_Bin-PT-170to300_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /QCD_Bin-PT-300to470_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
    vjets:
      datasets:
        - /DYto2E-4Jets_Bin-MLL-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
        - /DYto2Mu-4Jets_Bin-MLL-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v3/MINIAODSIM
        - /WtoLNu-4Jets_Bin-1J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /WtoLNu-4Jets_Bin-2J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /WtoLNu-4Jets_Bin-3J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
        - /WtoLNu-4Jets_Bin-4J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
    single_top:
      dataset_queries:
        - /ST*_TuneCP5_13p6TeV*/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v*/MINIAODSIM
