mode: dilepton_emu_os  # exactly one muon + one electron with opposite sign

hlt_by_era:
  UL16:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_IsoTkMu24_v*"
      - "HLT_Ele27_WPTight_Gsf_v*"
  UL17:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu27_v*"
      - "HLT_Ele32_WPTight_Gsf_L1DoubleEG_v*"
      - "HLT_Ele35_WPTight_Gsf_v*"
  UL18:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"
  Run3_22:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Mu50_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"
  Run3_22EE:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Mu50_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"
  Run3_23:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"
  Run3_23BPix:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"
  Run3_24:
    apply: true
    process: "HLT"
    paths:
      - "HLT_IsoMu24_v*"
      - "HLT_Ele32_WPTight_Gsf_v*"

jets:
  min_njets: 0
  max_njets: 4
  min_pt: 20.0
  max_eta: 2.5
  jet_id: "tight"  # "loose" | "tight" | "tightLepVeto" | "" (disable)
  jet_lepton_overlap_dr: 0.4

leptons:
  max_nleptons: 2
  muon_min_pt: 20.0
  muon_max_eta: 2.4
  muon_id: "loose"
  muon_max_rel_iso04: 0.25
  electron_min_pt: 25.0
  electron_max_eta: 2.5
  electron_id: "loose"
  electron_max_rel_iso03: 0.25
